// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSCodeGENExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "CSCodeGENExtension.97941be0-b3b3-4fbd-b280-a999c23a1a19";
        public const string Name = "CSCodeGENExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
