name: Build WinForms EXE

on:
  push:
    branches: [ "main", "master" ]  # Passe ggf. an

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish WinForms App
      run: dotnet publish CSCodeGen/CSCodeGen.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

    - name: Upload .exe Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WinForms-App
        path: CSCodeGen/bin/Release/net8.0/win-x64/publish/*.exe
