name: Build and Upload CSCodeGenApp
 
on:
   push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore CSCodeGenApp.CodeGen/CSCodeGenApp.CodeGen.csproj

      - name: Build project
        run: dotnet build CSCodeGenApp.CodeGen/CSCodeGenApp.CodeGen.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish CSCodeGenApp.CodeGen/CSCodeGenApp.CodeGen.csproj --configuration Release --runtime win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true --output publish

      - name: List output files
        run: |
          dir publish

      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSCodeGenApp
          path: publish/*.exe
