name: Build WinForms EXE

on:
  push:
    branches: [ "main", "master" ]  # Passe an deine Branches an

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Oder deine verwendete Version

    - name: Restore dependencies
      run: dotnet restore CSCodeGen.sln

    - name: Build & publish WinForms project
      run: dotnet publish CSCodeGenApp.CodeGen/CSCodeGenApp.CodeGen.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: WinFormsApp
        path: CSCodeGenApp/Build/Release/net8.0-windows/*.exe
