name: Build and Publish WinForms App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish Application
      run: dotnet publish CSCodeGenApp.CodeGen/CSCodeGenApp.CodeGen.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true

    - name: Zeige Verzeichnisstruktur (PowerShell)
      shell: pwsh
      run: Get-ChildItem -Recurse -Path CSCodeGenApp | Select-Object FullName

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: WinFormsApp
        path: CSCodeGenApp/bin/Release/net8.0-windows/win-x64/publish/*.exe
        if-no-files-found: warn
